services:
  uptimekuma-app:
    image: docker.io/nfrastack/uptimekuma:latest
    container_name: uptimekuma-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptimekuma-app.rule=Host(`uptimekuma.example.com`)
      - traefik.http.services.uptimekuma-app.loadbalancer.server.port=80
    volumes:
      - ./data:/app/data
      - ./logs/:/logs/
    environment:
      - TIMEZONE=America/Vancouver
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
